title: "The SemiFinals"
baseURL: "https://thesemifinals.org"
languageCode: "en-us"
theme:
  - github.com/theNewDynamic/gohugo-theme-ananke
DefaultContentLanguage: en
SectionPagesMenu: "main"

languages:
  en:
    title: "The SemiFinals"
    contentDir: "content/en"
params:
  mainSections:
    - blog
  ananke_socials:
    - name: discord
      label: Join Discord
      url: https://discord.gg/FffAzXD2s9
